remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

locale: "tr-TR"
title: "Yol Projeleri Blog"
subtitle: ""
name: "Fatma"
description: "Yol projeleri ve detayları"
url: "https://cngftsm.github.io"
repository: "cngftsm/cngftsm.github.io"

# Site Ayarları
search: true
search_full_content: true

# Yazar Bilgileri
author:
  name: "Fatma"
  bio: "Yol projeleri üzerine çalışmalar"
  location: "Türkiye"

# Varsayılan Sayfa Ayarları
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
