remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

locale: "tr-TR"
title: "Yol Projeleri Blog"
subtitle: ""
name: "[Adınız]"
description: "Yol projeleri ve detayları"
url: "https://[kullaniciadi].github.io"
repository: "[kullaniciadi]/[kullaniciadi].github.io"

# Site Ayarları
search: true
search_full_content: true

# Yazar Bilgileri
author:
  name: "[Adınız]"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Yol projeleri üzerine çalışmalar"
  location: "Türkiye"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/[kullaniciadi]"

# Varsayılan Sayfa Ayarları
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
