remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark

# Site settings
locale: "tr-TR"
title: "Yol Projeleri Blog"
description: "Yol projeleri ve detayları"
url: "https://cngftsm.github.io"
baseurl: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap

# Site Author
author:
  name: "Fatma"
  bio: "Yol projeleri üzerine çalışmalar"
  location: "Türkiye"

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
